/*
The contents of this file are subject to the Mozilla Public License
Version 1.1 (the "License"); you may not use this file except in
compliance with the License. You may obtain a copy of the License at
http://www.mozilla.org/MPL/

Software distributed under the License is distributed on an "AS IS"
basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
License for the specific language governing rights and limitations
under the License.

The Original Code is pocketSOAP.

The Initial Developer of the Original Code is Simon Fell.
Portions created by Simon Fell are Copyright (C) 2002
Simon Fell. All Rights Reserved.

Contributor(s):
*/

// InterfaceFinder.cpp : Implementation of CInterfaceFinder

#include "stdafx.h"
#include "PSOAP.h"
#include "InterfaceFinder.h"

/////////////////////////////////////////////////////////////////////////////
// CInterfaceFinder
/////////////////////////////////////////////////////////////////////////////

// note, this is primary aimed at being used with the VB6 classes generated by the WSDL wizard
STDMETHODIMP CInterfaceFinder::DefaultIID(/*[in]*/ BSTR theClass, /*[out,retval]*/ BSTR * iid )
{
	CLSID clsid ;
	_HR(CLSIDFromString(theClass, &clsid)) ;
	
	CComPtr<IUnknown> punk ;
	_HR(punk.CoCreateInstance(clsid)) 
	CComPtr<IDispatch> pdisp ;
	_HR(punk.QueryInterface(&pdisp)) 

	UINT tic = 0 ;
	pdisp->GetTypeInfoCount(&tic) ;
	if ( tic == 0 )
		return E_FAIL ;
	
	CComPtr<ITypeInfo> ti ;
	_HR(pdisp->GetTypeInfo(0, LOCALE_SYSTEM_DEFAULT, &ti ) )
	TYPEATTR * pta =0 ;
	_HR(ti->GetTypeAttr(&pta)) ;
	CComBSTR guid(pta->guid) ;
	*iid = guid.Detach() ;
	
	return S_OK ;
}